import { Element } from 'react-scroll';
import { Link } from 'react-router-dom';
import React, { Fragment } from 'react';
import { LayoutBase, Content } from '../../components/Layout';
import VerticalMenu from '../../components/VerticalMenu';
import Footer from '../../components/Footer';
import { PanelHashWrapper } from '../../components/Panel';
import { getUosGroupId } from '../../utils/config';
import urls from '../../utils/urls';
import styles from './styles.css';

const Faq = () => (
  <LayoutBase>
    <Content>
      <div className={styles.container}>
        <h1 className={styles.title}>FAQ</h1>
        <div className={styles.content}>
          <div className={styles.sidebar}>
            <VerticalMenu
              sticky
              sections={[
                { name: 'U°Community', title: 'U°Community' },
                { name: 'U°OS', title: 'U°OS' },
                { name: 'Glossary', title: 'Glossary' },
              ]}
            />
          </div>

          <div className={styles.main}>
            {[{
              title: 'U°Community',
              items: [
                {
                  id: 'question-1',
                  title: 'What is U°community?',
                  content: (
                    <p>
                      U°Community is a dapp on the U°OS blockchain. U°Community allows you to create content, interact with people, use dapps, run your business, govern Decentralized Autonomous Organizations (DAO) and Decentralized Autonomous Communities (DAC) and many other things.
                      Your contributions to the network through U°Community are decentrally weighed by the community. The resulting weight of your contributions is your influence score called Importance. Your Importance is your digital asset.
                    </p>
                  ),
                },
                {
                  id: 'question-2',
                  title: 'How can people interact on the platform?',
                  content: (
                    <Fragment>
                      <p>People on the U°Community platform can interact with each other using:</p>
                      <ul>
                        <li>Follow – Subscribe to the content generated by the user</li>
                        <li>Join — Join <a href="#question-46" className="link red">Community</a></li>
                        <li>Trust — A social transaction with which you extend your web of trust to other accounts: people and <a className="link red" href="#question-54">Organizations</a></li>
                        <li>Repost – Create a post in your personal feed with a short preview and a link to the reposted content, much like a Twitter or Facebook repost</li>
                        <li>Upvote — A social transaction with which you give value to posts with your Importance</li>
                        <li>Downvote — The opposite of Upvote</li>
                      </ul>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-3',
                  title: 'What can I do as an unregistered user?',
                  content: (
                    <p>You can see all the content produced by other users on the entirety of U°Community.</p>
                  ),
                },
                {
                  id: 'question-4',
                  title: 'What can I do as a registered user?',
                  content: (
                    <Fragment>
                      <p>You can see all the content produced by other users and interact with other users and content.</p>
                      <p>You can create your own content.</p>
                      <p>Other users will be able to interact with your profile and with your content.</p>
                      <p>You can shape your own interests by following the people and communities you like.</p>
                      <p>You can interact with all the content on the platform: like, comment and share posts, sell and purchase goods and services via offers, run and join a <a href="#question-46" className="link red">Community</a> and/or an <a href="#question-54" className="link red">Organization</a>.</p>
                      <p>You can transfer funds to other registered users. </p>
                      <p>You can (and should) vote for <a href="#question-43" className="link red">Block Producers</a> and <a href="#question-45" className="link red">Calculator Nodes</a> on the <Link to={urls.getGovernanceUrl()} className="link red">governance page.</Link></p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-5',
                  title: 'How do I register? What information do you need?',
                  content: (
                    <Fragment>
                      <p>You can register by clicking SIGN IN —&gt; Create one in the header.</p>
                      <p>You need to generate a <a href="#question-38" className="link red">unique account name</a> and save the <a href="#question-44" className="link red">Brainkey</a> in any convenient way. If you lose your Brainkey, your account will be lost. Please take your time to properly save and secure the Brainkey.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-6',
                  title: 'Can I change or recover my password?',
                  content: (
                    <Fragment>
                      <p>No. U°Community is a dapp on blockchain. Your account is an account on blockchain that you can only access with your <a href="#question-44" className="link red">brainkey</a>.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-7',
                  title: 'What entities can I create?',
                  content: (
                    <Fragment>
                      <p>When you register on the platform, your personal user profile will be created. After that you can create:</p>
                      <ul>
                        <li>
                          Community profile – you can invite other users of the platform to the Community Board. See also <a href="#question-46" className="link red">DAC</a>.
                        </li>
                        <li>
                          Organization profile — you can invite other users of the platform to the Community Board. See also <a href="#question-54" className="link red">DAO</a>.
                        </li>
                      </ul>
                      <p>All the profiles (user, community, organization) have their own separate profile feed that they can use to distribute content to the users following them.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-8',
                  title: 'What can I post in my feed?',
                  content: (
                    <p>You can do short posts (like Twitter or Facebook short posts), you can create publications (longer posts like Medium) or you can create offers.</p>
                  ),
                },
                {
                  id: 'question-9',
                  title: 'Can I use Tags?',
                  content: (
                    <p>You can add #tags to your posts to gain visibility. Tags get their own <a href="#question-50" className="link red">Importance</a> based on how the tagged posts perform with the community.</p>
                  ),
                },
                {
                  id: 'question-10',
                  title: 'Can I mention other users?',
                  content: (
                    <p>Mention other registered users with @. For example, @accountName. The user that you mention will receive a notification.</p>
                  ),
                },
                {
                  id: 'question-11',
                  title: 'What are these degree signs above posts or profiles?',
                  content: (
                    <p><a href="#question-50" className="link red">Importance</a>.</p>
                  ),
                },
                {
                  id: 'question-12',
                  title: 'How is U°Community different from Steemit?',
                  content: (
                    <Fragment>
                      <p>Steemit is built around content, its rating and direct monetization.</p>
                      <p>U°Community is intrinsically different.</p>
                      <p>U°Community is a dapp on the U°OS blockchain that’s built to realize the three core concepts:</p>
                      <ul>
                        <li><a href="#question-49" className="link red">Digital individual</a></li>
                        <li><a href="#question-42" className="link red">Asset</a></li>
                        <li><a href="#question-53" className="link red">Network economy</a></li>
                      </ul>
                      <p>The content that you share on U°Community is a part of your interaction with the network, it’s not the sole objective of the dapp. Your social transactions are registered on the blockchain, your content is evaluated by the network members, and as a result you are decentrally assigned <a href="#question-50" className="link red">Importance</a>. Importance is your asset that you — a <a href="#question-49" className="link red">Digital individual</a> — use in the network economy, which is basically a peer-to-peer economy. You can scale your Importance effortlessly by using it as a decentrally established reputation — e.g. by using it as a trusted LinkedIn profile, you can run your business as an <a href="#question-54" className="link red">Organization</a>, you can influence the network with your Importance, you can put out a dapp for people to use and it will run off your Importance alone, without spending money on ads and so on — the opportunities are endless.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-13',
                  title: 'How is U°Community different from Reddit?',
                  content: (
                    <Fragment>
                      <p>Lots of great communities live on Reddit and the Karma you get for contributing to the communities there is what’s called “Imaginary Internet Points”.</p>
                      <p>U°Community uses the U°OS network’s <a href="#question-48" className="link red">DPOI</a>, which means your “karma” here — called Importance — really matters. Through <a href="#question-50" className="link red">Importance</a> you have influence on anything on the network — from being a part of decision making processes through decentral governance to becoming a part of the active economy by having the network’s native currency — UOS — issued to you based on your <a href="#question-50" className="link red">Importance</a>.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-14',
                  title: 'Can I fake my activity on U°Community to increase my Importance?',
                  content: (
                    <p>The algorithm of U°Community and U°OS is completely transparent with zero obfuscation and designed to run a network where real human contribution is valued the most. For details, check <a target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/tree/master/yellow_paper" className="link red">the Yellow Paper on U°OS Network GitHub.</a></p>
                  ),
                },
                {
                  id: 'question-15',
                  title: 'Is this totally like that Black Mirror episode?',
                  content: (
                    <Fragment>
                      <p>No. This is not the total surveillance system that people fear, it’s the opposite.</p>
                      <p>In a total surveillance system where you get assigned a social score, you don’t choose how to manifest yourself in a community. On U°Community, you do. It’s you operating as a sovereign <a href="#question-49" className="link red">Digital individual</a>, not as a tracked, monitored, and surveilled unit.</p>
                      <p>A surveillance system is a centralized entity that centrally decides what score to assign to you. Both U°Community and U°OS are decentralized and belong to the network.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-16',
                  title: 'Who is building U°Community?',
                  content: (
                    <p>Check the <Link className="link red" target="_blank" to={urls.getOrganizationUrl(getUosGroupId())}>board of U°OS Network.</Link> We are a team that believes in the sovereignty of the <a href="#question-49" className="link red">Digital individual</a> and in the <a href="#question-53" className="link red">Network economy</a>.</p>
                  ),
                },
                {
                  id: 'question-17',
                  title: 'Where can I check the code of U°Community?',
                  content: (
                    <p>Check <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/">U°OS Network on GitHub.</a></p>
                  ),
                },
                {
                  id: 'question-18',
                  title: 'Can I contribute to the code of U°Community?',
                  content: (
                    <Fragment>
                      <p>Please do! U°Community is open source and the development community is growing.</p>
                      <p>Start with <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/blob/master/CONTRIBUTING.md">CONTRIBUTING.md of U°OS Network on GitHub.</a> We keep it up to date.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-19',
                  title: 'Is U°Community on a testnet right now?',
                  content: (
                    <p>Yes.</p>
                  ),
                },
                {
                  id: 'question-20',
                  title: 'When will U°Community migrate to mainnent?',
                  content: (
                    <p>There’s no specific date. Your best bet is around mid 2019.</p>
                  ),
                },
                {
                  id: 'question-21',
                  title: 'Why should I become a part of the U°Community testnet?',
                  content: (
                    <p>A pool of the mainnet UOS tokens will be distributed to the testnet accounts in accordance with each account’s <a href="#question-50" className="link red">Importance</a>. Apart from being a testnet participation incentive, this is a good way to kickstart the mainnet.</p>
                  ),
                },
                {
                  id: 'question-22',
                  title: 'Are there any airdrops of UOS planned?',
                  content: (
                    <p>To jumpstart the network, there will be airdrops to holders of tokens and coins of other networks. The details will be announced later.</p>
                  ),
                },
                {
                  id: 'question-23',
                  title: 'Will UOS be tradable on exchanges?',
                  content: (
                    <p>Exchange listings are being negotiated, but only for the mainnet tokens. The testnet tokens are just this — testnet tokens.</p>
                  ),
                },
              ],
            }, {
              title: 'U°OS',
              items: [
                {
                  id: 'question-24',
                  title: 'What is U°OS?',
                  content: (
                    <p>U°OS is a <a href="#question-48" className="link red">DPOI</a> based distributed protocol framework. U°OS is based on the EOSIO open-source code.</p>
                  ),
                },
                {
                  id: 'question-25',
                  title: 'How is U°OS different from other blockchains?',
                  content: (
                    <p>U°OS is based on the new <a href="#question-48" className="link red">DPOI</a> (Delegated Proof of Importance) consensus algorithm. Importance is your influence score in the network and it’s decentrally assigned based on how the community values your contributions. U°OS issues the native core token called UOS based on your <a href="#question-50" className="link red">Importance</a>.</p>
                  ),
                },
                {
                  id: 'question-26',
                  title: 'How is U°OS different from EOSIO?',
                  content: (
                    <p>The main difference is the consensus algorithm – <a href="#question-48" className="link red">DPOI</a> (Delegated Proof of Importance).</p>
                  ),
                },
                {
                  id: 'question-27',
                  title: 'What features does U°OS have?',
                  content: (
                    <ul>
                      <li>Smart-contracts execution</li>
                      <li>Currencies and tokens support</li>
                      <li>WebAssembly support</li>
                      <li>Account system</li>
                      <li>Free for applications’ users</li>
                      <li>Dynamic emission algorithm</li>
                      <li>Social transactions</li>
                      <li>Asset Transfer</li>
                      <li>Social Importance</li>
                      <li>DAC and DAO support</li>
                    </ul>
                  ),
                },
                {
                  id: 'question-28',
                  title: 'Can U°OS be used by other applications?',
                  content: (
                    <p>Yes, it can be used by other applications – U°Community is just one of the use-cases for the U°OS network.</p>
                  ),
                },
                {
                  id: 'question-29',
                  title: 'How are social interactions reflected on the blockchain?',
                  content: (
                    <p>Every social interaction that users perform using the U°Community dapp is registered in the U°OS blockchain as a transaction. So every action is immutably recorded.</p>
                  ),
                },
                {
                  id: 'question-30',
                  title: 'Can the Importance algorithm be used by other applications on the U°OS blockchain?',
                  content: (
                    <p>Yes, the library is open-source and can be used by any developers that want to launch their own dapps.</p>
                  ),
                },
                {
                  id: 'question-31',
                  title: 'Who is building U°OS?',
                  content: (
                    <Fragment>
                      <p>
                        Check the <Link className="link red" target="_blank" to={urls.getOrganizationUrl(getUosGroupId())}>board of U°OS Network </Link>
                        and the <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/orgs/UOSnetwork/people">U°OS Network GitHub.</a> We are a group of people that believe in the sovereignty of the <a href="#question-49" className="link red">Digital individual</a> and in the <a href="#question-53" className="link red">Network economy</a>.
                      </p>
                      <p>You are more than welcome to join us.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-32',
                  title: 'Where can I check the code of U°OS?',
                  content: (
                    <p>Check <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/">U°OS Network on GitHub.</a></p>
                  ),
                },
                {
                  id: 'question-33',
                  title: 'Can I contribute to the code of U°OS?',
                  content: (
                    <Fragment>
                      <p>Please do! U°OS is open source and the development community is growing.</p>
                      <p>Start with <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/blob/master/CONTRIBUTING.md">CONTRIBUTING.md of U°OS Network on GitHub.</a> We keep it up to date.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-34',
                  title: 'Technical details of DPOI?',
                  content: (
                    <p>Check the <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/tree/master/yellow_paper">DPOI Yellow Paper on U°OS Network GitHub.</a></p>
                  ),
                },
                {
                  id: 'question-35',
                  title: 'Is U°OS on a testnet right now?',
                  content: (
                    <p>Yes.</p>
                  ),
                },
                {
                  id: 'question-36',
                  title: 'When will U°OS migrate to mainnent?',
                  content: (
                    <p>There’s no specific date. Your best bet is around mid 2019.</p>
                  ),
                },
                {
                  id: 'question-37',
                  title: 'Are there any airdrops of UOS planned?',
                  content: (
                    <p>To jumpstart the network, there will be airdrops to holders of tokens and coins of other networks. The details will be announced later.</p>
                  ),
                },
              ],
            }, {
              title: 'Glossary',
              items: [
                {
                  id: 'question-38',
                  title: 'Account',
                  content: (
                    <Fragment>
                      <p>An account is your collection of authorizations registered on the U°OS blockchain.</p>
                      <p>Your account has a human-readable name, a brainkey, public-private key pairs, and owner and active permissions.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-39',
                  title: 'Account creation',
                  content: (
                    <Fragment>
                      <p>To create an account:</p>
                      <ol>
                        <li>Click SIGN IN —&gt; Create one</li>
                        <li>Type in your preferred account name.</li>
                        <li>Click PROCEED.</li>
                        <li>Copy your brainkey and store it in a secure place.</li>
                        <li>Verify your brainkey by crossing out the words 2, 4, 8 and 12 of your brainkey in the randomized key order.</li>
                        <li>If you accept the terms and conditions, put a tick in the box.</li>
                        <li>Click FINISH.</li>
                      </ol>
                      <p>The U°OS blockchain will register the account name.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-40',
                  title: 'Account name',
                  content: (
                    <Fragment>
                      <p>An account name is a name that you pick and register on the U°OS blockchain.</p>
                      <p>The account name is linked to your brainkey and the public-private key pairs.</p>
                      <p>The account name has the following conventions:</p>
                      <ul>
                        <li>Must be 12 characters</li>
                        <li>Can only contain the characters abcdefghijklmnopqrstuvwxyz12345, a-z (lowercase), 1-5</li>
                      </ul>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-41',
                  title: 'Active permission',
                  content: (
                    <p>The active permission has an associated key that you use to sign your fund transfer transactions.</p>
                  ),
                },
                {
                  id: 'question-42',
                  title: 'Asset',
                  content: (
                    <Fragment>
                      <p>An asset is what the <a href="#question-49" className="link red">digital individual</a> possesses. An asset is a value you bring to the network by operating as a digital individual; it&#39;s what you contribute to the network and the many communities on the network. On Reddit, it&#39;s your karma points; on Facebook, it&#39;s the likes that your posts get and followers; on Steemit, it&#39;s your followers and your Steem Dollars and your Steem Power, and so on. So the asset is what you have as a result of your social transactions — e.g., do a post in a network, be evaluated by the community (e.g., through upvotes/downvotes) that have any interest in the knowledge you are sharing, receive incoming social transactions through upvotes and comments/replies. This is your social asset.</p>
                      <p>But an asset is also what you need to have in the form of currency to operate as a business and as a customer. For example, when you need to buy/sell something (including physical goods) on the network, you use currency. It&#39;s an economic transaction. The native U°OS and U°Community token is called UOS. You use <a href="#question-61" className="link red">UO</a> for economic transactions — to run a dapp or do any sort of business. You also receive UOS for your social transactions.</p>
                      <p>See also <a href="#question-50" className="link red">Importance</a>.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-43',
                  title: 'Block Producer',
                  content: (
                    <p>A block producer is a role on the U°OS blockchain that produces blocks. Every transaction on the U°OS blockchain is registered in a block by a block producer. A block producer is voted into the role by the community.</p>
                  ),
                },
                {
                  id: 'question-44',
                  title: 'Brainkey',
                  content: (
                    <Fragment>
                      <p>A brainkey is the seed phrase used to generate public-private key pairs. The brainkey is linked to your account name.</p>
                      <p>Use the brainkey to access your account and register transactions on the U°OS blockchain.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-45',
                  title: 'Calculator Node',
                  content: (
                    <Fragment>
                      <p>A Calculator Node is a node on the U°OS blockchain dedicated to calculating the activity of your account: social, transactional, stake.</p>
                      <p>Calculator Nodes are community-owned and receive a regular emission of UOS tokens.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-46',
                  title: 'Community',
                  content: (
                    <Fragment>
                      <p>A community is a Decentralized Autonomous Community (DAC) that you can create or join.</p>
                      <p>Create or become a part of a community to work with other members to increase or diversify your influence.</p>
                      <p>You can add your publications on your behalf or on behalf of a community that you joined. Adding a publication on behalf of a community increases your audience reach.</p>
                      <p>Governance is a key feature to running your community decentrally.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-47',
                  title: 'Delay on social/transactional activity',
                  content: (
                    <p>There might be a delay on your social activity, including upvoting, because your actions are registered on the U°OS blockchain.</p>
                  ),
                },
                {
                  id: 'question-48',
                  title: 'Delegated Proof of Importance',
                  content: (
                    <Fragment>
                      <p>DPOI is the consensus algorithm of U°OS. For anything on the network, including the network changes, you vote with your <a href="#question-50" className="link red">Importance</a>. DPOI is what keeps the network live.</p>
                      <p>For details, check the <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/tree/master/yellow_paper">Yellow Paper on U°OS Network GitHub.</a></p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-49',
                  title: 'Digital individual',
                  content: (
                    <p>The digital individual is your digital representation in the network — basically the Internet. Your digital selfhood.</p>
                  ),
                },
                {
                  id: 'question-50',
                  title: 'Importance',
                  content: (
                    <Fragment>
                      <p>Importance is both a reputation and an asset on the network.</p>
                      <p>You get assigned an Importance based on the following factors:</p>
                      <ul>
                        <li>UOS Stake — The amount of UOS you stake for network resources</li>
                        <li>Social transactions — Upvotes, Downvotes, Comments, Replies you receive as a result of you operating in the network</li>
                        <li>Economic transactions — Transfer of funds in the form of UOS to you</li>
                      </ul>
                      <p>For details, check the <a className="link red" target="_blank" rel="noopener noreferrer" href="https://github.com/UOSnetwork/uos.docs/tree/master/yellow_paper">Yellow Paper on U°OS Network GitHub.</a></p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-51',
                  title: 'Importance decay',
                  content: (
                    <p>Your Importance fades over time based on your social and transactional activity parameter. If your account stays socially or transactionally inert for a period of time, your Importance decays.</p>
                  ),
                },
                {
                  id: 'question-52',
                  title: 'Mentions',
                  content: (
                    <p>Mention other users with @AccountName. The users that you mention will receive a notification.</p>
                  ),
                },
                {
                  id: 'question-53',
                  title: 'Network economy',
                  content: (
                    <p>A network economy — a term that in 2019 still has no clear definition — is pretty much the way anyone with access to a connected device operates today. Kevin Kelly formulated the 12 principles of the network economy — and these are the principles that U°OS is based on — in 1997 in a Wired article and expanded on them in a book in 1998. In 2018 Kevin Kelly also said that it&#39;d been 20 years and he wouldn&#39;t change much in the principles he had formulated. They stood the test of time. Check out the original article: <a className="link red" target="_blank" rel="noopener noreferrer" href="https://www.wired.com/1997/09/newrules/">Wired: New Rules for New Economy</a> and there&#39;s also a good summary: <a className="link red" target="_blank" rel="noopener noreferrer" href="https://u.community/posts/3525">The Network Economy: 20 Years and 12 Principles</a>.</p>
                  ),
                },
                {
                  id: 'question-54',
                  title: 'Organization',
                  content: (
                    <Fragment>
                      <p>An organization is a Decentralized Autonomous Organization (DAO) that you can create or join through an invitation.</p>
                      <p>DAOs are the best way to run your business in a decentralized and transparent way.</p>
                      <p>Governance is a key feature to running your organization decentrally.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-55',
                  title: 'Owner permission',
                  content: (
                    <Fragment>
                      <p>The owner permission has an associated key that you use to change the active permission. The owner key represents the ownership of your account.</p>
                      <p>This is your owner key to change the active permission.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-56',
                  title: 'Profile',
                  content: (
                    <Fragment>
                      <p>A profile is your publicly visible information.</p>
                      <p>Filling out the profile is an excellent way to let the community learn about you and engage.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-57',
                  title: 'Social activity',
                  content: (
                    <Fragment>
                      <p>Your social activity represents your social interactions on the U°OS blockchain: your publications, comments, upvotes, evaluation of your actions by the community, including your actions and posts as part of your registered communities.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-58',
                  title: 'Tags',
                  content: (
                    <Fragment>
                      <p>You can add #tags to your posts to gain visibility. Tags get their own Importance based on how the tagged posts perform with the community.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-59',
                  title: 'Transactional activity',
                  content: (
                    <Fragment>
                      <p>Your transactional activity represents transfer of funds to your account from various accounts on the U°OS blockchain.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-60',
                  title: 'Trust',
                  content: (
                    <Fragment>
                      <p>Trust is a social transaction on the network from one account to another. When you click “Trust” on an organization or an individual, you extend your web of trust to them.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-61',
                  title: 'UOS token',
                  content: (
                    <Fragment>
                      <p>UOS is the native token of U°OS network. You can use it currency and for staking to buy and rent network resources</p>
                      <p>On the network, you get UOS by:</p>
                      <ul>
                        <li>Running a <a href="#question-43" className="link red">Block Production Node</a></li>
                        <li>Running a <a href="#question-45" className="link red">Calculator Node</a></li>
                        <li>For your <a href="#question-50" className="link red">Importance</a></li>
                        <li>Account to account transfer — for example, by running an <a href="#question-54" className="link red">Organization</a></li>
                        <li>Dapp monetization</li>
                      </ul>
                      <p>Outside of the network, you can get UOS by purchasing it on an exchange when it’s listed.</p>
                    </Fragment>
                  ),
                },
                {
                  id: 'question-62',
                  title: 'UOS token emission',
                  content: (
                    <Fragment>
                      <p>The emission is a regular emission of UOS tokens to the accounts registered on the U°OS blockchain.</p>
                      <p>The emission has two broad types:</p>
                      <ul>
                        <li>Regular emission to Block Producers and Calculator Nodes</li>
                        <li>Dynamic emission to user accounts based on their Importance</li>
                      </ul>
                    </Fragment>
                  ),
                },
              ],
            }].map((item, index) => (
              <Element name={item.title} key={index}>
                <h2 className={styles.subTitle}>{item.title}</h2>

                {item.items.map((item, index) => (
                  <div className={styles.item} key={index}>
                    <div id={item.id} className={styles.anchor} />
                    <PanelHashWrapper
                      title={item.title}
                      hash={`#${item.id}`}
                    >
                      <div className={styles.text}>{item.content}</div>
                    </PanelHashWrapper>
                  </div>
                ))}
              </Element>
            ))}
          </div>
        </div>

        <Footer />
      </div>
    </Content>
  </LayoutBase>
);

export default Faq;
